import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Coder's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
          <h1 className={styles.title}>The Coder's Blog</h1>
        
        <div className={styles.blogs}>
          <div className={styles.blogItem}>
            <h2>How to learn NextJS in 1 day!</h2>
            <p>You cant do that...!</p>
          </div>
          <div className={styles.blogItem}>
            <h2>Difference in React and NextJS</h2>
            <p>There is no difference between these two..!</p>
          </div>
          <div className={styles.blogItem}>
            <h2>Difference in React and NextJS</h2>
            <p>There is no difference between these two..!</p>
          </div>
          <div className={styles.blogItem}>
            <h2>Difference in React and NextJS</h2>
            <p>There is no difference between these two..!</p>
          </div>
        </div>
        </main>
    </>
  )
}
